make file to check for region and IAM role

diff --git a/Project/studentapp/final/Makefile b/Project/studentapp/final/Makefile
--- a/Project/studentapp/final/Makefile
+++ b/Project/studentapp/final/Makefile
@@ -10,13 +10,14 @@ help:
 
 checks:
 	@if [ -z "${IAM_ROLE}" ]; then
-		echo "Role Missing to run the code"
-		exit 1
-	fi
-	@if [ -z "${AWS_DEFAULT_REGION}" ]; then
-		echo -e "Region is missing, export the AWS_DEFAULT_REGION variable"
-		exit 1
-	fi
+    	echo "Role Missing to run the code"
+    	exit 1
+    fi
+    @if [ -z "${AWS_DEFAULT_REGION}" ]; then
+    	echo -e "Region Missing, Variable AWS_DEFAULT_REGION needs to be exported"
+    	exit 1
+    fi
+
 dev-init: checks
 	@cd ENV/DEV
 	@git pull
